### ISSUE TITLE
добавить поддержку 1.16.5

### ISSUE THREAD

**Issue by Medved0546** [getplusm/Dungeons#1]
добавить поддержку популярной 1.16.5

**Comment by getplusm** [comment]
Прости, но для меня это устаревшая версия

**Comment by Medved0546** [comment]
да это не устаревшая версия а те просто лень))

**Comment by getplusm** [comment]
> да это не устаревшая версия а те просто лень))

Мне не лень и я не сказал, что она устаревшая для всех)
